FROM openjdk:17.0-slim

EXPOSE 8080

ARG PROJECT_DIRECTORY=/build
WORKDIR %PROJECT_DIRECTORY

ARG JAR_FILE_PATH=build/libs/server-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE_PATH} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]