server:
  port: ${PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    url: ${URL}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        default_batch_fetch_size: 50
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTPEMAIL}
    password: ${SMTPPASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  redis:
    host: ${REDISHOST}
    port: ${REDISPORT}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}
  access-token-validTime: ${JWT_ACCESS_TOKEN_VALID_TIME}
  refresh-token-validTime: ${JWT_REFRESH_TOKEN_VALID_TIME}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}

springdoc:
  swagger-ui:
    url: /v3/api-docs
    urls-primary-name: Gloddy

